version: "3"
services:
  redis:
    image: redis
    volumes:
      - ../../tmp/db/redis:/var/lib/redis/data

  fs_streamer_nginx:
    build:
      dockerfile: ./Dockerfile.fs_streamer_nginx
      context: ./
    ports:
      - "8081:8081"
    depends_on:
      - fs_streamer_rack

  fs_streamer_rack:
    stdin_open: true
    build:
      dockerfile: ./dev/docker/Dockerfile
      context: ../../
    command: bash -c "bundle exec puma -b 'tcp://0.0.0.0:9292'"
    environment:
      - AUTHORIZATION_ENDPOINT=http://fs_upstream_api:8083/authorize
      - REPORT_ENDPOINT=http://fs_upstream_api:8083/report
      - REDIS_URI=redis://redis:6379/0
    volumes:
      - ../../:/app
    ports:
      - "9292:9292"
    depends_on:
      - redis

  fs_upstream_api:
    build:
      dockerfile: ./Dockerfile.fs_upstream_api
      context: ./
    ports:
      - "8083:8083"

  file_server:
    build:
      dockerfile: ./Dockerfile.file_server
      context: ./
    volumes:
      - ../../test/spec/fixtures:/usr/share/nginx
    ports:
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
